name: tests

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - "*.*.*"

  pull_request:
    branches:
      - main

env:

  package-name: amltk
  test-dir: tests
  extra-requires: "[dev]"  # "" for no extra_requires

jobs:
  test:

    name: ${{ matrix.python-version }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash # Default to using bash on all

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"] # "3.12" doesn't work because of ConfigSpace for some reason.
        os: ["ubuntu-latest"] # Disable mac and windows until time to fix pynisher, "macos-latest", "windows-latest"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Install ${{ env.package-name }}
      run: |
        python -m pip install -e ".${{ env.extra-requires }}"

    - name: Tests
      run: |
        pytest ${{ env.test-dir }}
